cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    stack:
      auto:
  mapbox:
    token:

application:
  bucket:
    name:
  security:
    secret-key:

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

twilio:
  account_sid:
  auth_token:
  trial_phone: