cloud:
  aws:
    credentials:
      access-key: AKIAXXTFF2PMREK7FGTT
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false
  mapbox:
    token: pk.eyJ1Ijoic2l4YmxhY2siLCJhIjoiY2w0dzNpYnVyMXFhYjNlazI5OGF6MGJzcyJ9.DMrrU3tLH2gfvfY1wK9G4w

application:
  bucket:
    name: encare
  security:
    secret-key: encare

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

twilio:
  account_sid: AC914bef40cbbb437f8bee775b4109ec6e
  auth_token: 7cc837a82b830f536332f464aba68427
  trial_phone: +16815324305