cloud:
  aws:
    credentials:
      access-key: AKIASRKRB2OB7HWIEADE
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false
  mapbox:
    token: pk.eyJ1Ijoic2l4YmxhY2siLCJhIjoiY2w0dzNpYnVyMXFhYjNlazI5OGF6MGJzcyJ9.DMrrU3tLH2gfvfY1wK9G4w

application:
  bucket:
    name: nts-encare
  security:
    secret-key: encare


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

twilio:
  account_sid: AC914bef40cbbb437f8bee775b4109ec6e
  auth_token: 490ca43ea5a95c9f33068b2f3578e7ff
  trial_phone: +16815324305